### ISSUE TITLE
Add `Convert<Option<TypeTagged>>` and `Convert<Vec<TypeTagged>>`

### ISSUE THREAD

**Issue by Shute052** [mintlu8/bevy_serde_project#1] opened 2024-04-10 20:17 UTC
Would it be possible to add these Converters? I would really appreciate it. They are essential for

- Leafwing-Studios/leafwing-input-manager#494

**Comment by mintlu8** [comment] 2024-04-11 12:11
I think these are entirely possible to be created by the user, see `bevy_stat_query` for a `BTreeMap<dyn T>` implementation. I'll see if I can come up with some good abstractions for these since they can be pretty common.

**Comment by mintlu8** [comment] 2024-04-11 17:12
The new `ProjectOption` and `ProjectVec` might fit this use case.

https://github.com/mintlu8/bevy_serde_project/releases/tag/0.2.0

**Comment by Shute052** [comment] 2024-04-12 06:07
How do they work with TypeTagged? I'm curious! This failed

```rust
#[serde_project("ProjectVec<Vec<TypeTagged<Box<dyn DualAxisProcessor>>>>")]
pub(crate) sequence: Vec<Box<dyn DualAxisProcessor>>,
```

**Comment by mintlu8** [comment] 2024-04-12 06:47
The first field should be an exact copy of the Vec's type, the second type (optional) is the projection of individual fields.

```rust
ProjectVec<Vec<Box<dyn DualAxisProcessor>>,  TypeTagged<Box<dyn DualAxisProcessor>>>"
```

**Comment by mintlu8** [comment] 2024-04-12 09:02
> But it seems like I'm running into another problem with recursive dyn Traits. It looks like Serialize, Deserialize, and SerdeProject can't play nice together, and the generated __Ser is out of reach from the outside.

All `Serialize` + `DeserializeOwned` structs are `SerdeProject` so you don't need the `SerdeProject` derive.

Closing this since the issue is solved.

**Closed by mintlu8** 2024-04-12 09:02 UTC
